export const CATALOG_ACTIVITY_ACTION = {
  CATEGORY_IMAGE_UPDATED: 'CATEGORY_IMAGE_UPDATED',
  CATEGORY_IMAGE_REMOVED: 'CATEGORY_IMAGE_REMOVED',

  BRAND_LOGO_UPDATED: 'BRAND_LOGO_UPDATED',
  BRAND_LOGO_REMOVED: 'BRAND_LOGO_REMOVED',

  STORE_LOGO_UPDATED: 'STORE_LOGO_UPDATED',
  STORE_LOGO_REMOVED: 'STORE_LOGO_REMOVED',

  STORE_CREATED: 'STORE_CREATED',
  STORE_UPDATED: 'STORE_UPDATED',
  STORE_DELETED: 'STORE_DELETED',
  PRODUCT_STORE_CHANGED: 'PRODUCT_STORE_CHANGED',
  CATEGORY_CREATED: 'CATEGORY_CREATED',
  CATEGORY_UPDATED: 'CATEGORY_UPDATED',
  CATEGORY_DELETED: 'CATEGORY_DELETED',

  BRAND_CREATED: 'BRAND_CREATED',
  BRAND_UPDATED: 'BRAND_UPDATED',
  BRAND_DELETED: 'BRAND_DELETED',

  PRODUCT_CREATED: 'PRODUCT_CREATED',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',
  PRODUCT_DELETED: 'PRODUCT_DELETED',

  PRODUCT_IMAGE_CREATED: 'PRODUCT_IMAGE_CREATED',
  PRODUCT_IMAGE_UPDATED: 'PRODUCT_IMAGE_UPDATED',
  PRODUCT_IMAGE_DELETED: 'PRODUCT_IMAGE_DELETED',

  PRODUCT_PUBLISHED: 'PRODUCT_PUBLISHED',
  PRODUCT_UNPUBLISHED: 'PRODUCT_UNPUBLISHED',

  PRODUCT_ARCHIVED: 'PRODUCT_ARCHIVED',
  PRODUCT_RESTORED: 'PRODUCT_RESTORED',

  PRODUCT_EXPIRATION_UPDATED: 'PRODUCT_EXPIRATION_UPDATED',
} as const;

export const CATALOG_RESOURCE_TYPE = {
  STORE: 'STORE',
  CATEGORY: 'CATEGORY',
  BRAND: 'BRAND',
  PRODUCT: 'PRODUCT',
  PRODUCT_IMAGE: 'PRODUCT_IMAGE',
} as const;
