export const CATALOG_ACTIVITY_ACTION = {
  CATEGORY_CREATED: 'CATEGORY_CREATED',
  CATEGORY_UPDATED: 'CATEGORY_UPDATED',
  CATEGORY_DELETED: 'CATEGORY_DELETED',

  BRAND_CREATED: 'BRAND_CREATED',
  BRAND_UPDATED: 'BRAND_UPDATED',
  BRAND_DELETED: 'BRAND_DELETED',

  PRODUCT_CREATED: 'PRODUCT_CREATED',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',
  PRODUCT_DELETED: 'PRODUCT_DELETED',

  PRODUCT_IMAGE_CREATED: 'PRODUCT_IMAGE_CREATED',
  PRODUCT_IMAGE_UPDATED: 'PRODUCT_IMAGE_UPDATED',
  PRODUCT_IMAGE_DELETED: 'PRODUCT_IMAGE_DELETED',

  PRODUCT_PUBLISHED: 'PRODUCT_PUBLISHED',
  PRODUCT_UNPUBLISHED: 'PRODUCT_UNPUBLISHED',
} as const;

export const CATALOG_RESOURCE_TYPE = {
  CATEGORY: 'CATEGORY',
  BRAND: 'BRAND',
  PRODUCT: 'PRODUCT',
  PRODUCT_IMAGE: 'PRODUCT_IMAGE',
} as const;
