export const GOVERNANCE_DEFAULT_PAGE = 1;
export const GOVERNANCE_DEFAULT_LIMIT = 20;
export const GOVERNANCE_MAX_LIMIT = 100;

export const GOVERNANCE_ACCOUNT_STATUSES = [
  'ACTIVE',
  'BLOCKED',
] as const;

export type GovernanceAccountStatus =
  (typeof GOVERNANCE_ACCOUNT_STATUSES)[number];

export const GOVERNANCE_ACTIVITY_ACTION = {
  SUPERADMIN_BOOTSTRAPPED:
    'SUPERADMIN_BOOTSTRAPPED',

  ADMIN_CREATED:
    'ADMIN_CREATED',

  CUSTOMER_BLOCKED:
    'CUSTOMER_BLOCKED',

  CUSTOMER_UNBLOCKED:
    'CUSTOMER_UNBLOCKED',

  ADMIN_BLOCKED:
    'ADMIN_BLOCKED',

  ADMIN_UNBLOCKED:
    'ADMIN_UNBLOCKED',
} as const;
